### ISSUE TITLE
Have the lib test with OCPP Compliancy Tool

### ISSUE THREAD

**Issue by foluswen** [ChargeTimeEU/Java-OCA-OCPP#16]
Hello, recently I use this lib to test with "OCPP Compliancy Tool" from OCA?.

When I connect to server create by "OCPP Compliancy Tool", always get connection close event, then can not do next step test.

So, I want to check with you, do you ever face the issue same with me?.....

**Comment by TVolden** [comment]
Hi there,

Thanks for your feedback.
I'm very​ interested in what you have learned and would like to know more. Do you use SOAP? Do you get any exceptions? Maybe some from the log.

I have experienced that the SOAP client/server close the connection prematurely. This was mainly due to the envelop/header. 

I haven't tested the lib against the official compliance tool, since it's quite expensive and my budget consist mostly of time :-)

You are welcome to email me at tv@chargetime.eu or join us on gitter and we can try to help.

Looking forward to hear more.

**Comment by foluswen** [comment]
Thank for your response.

 I use JSON with websocket, and does not find any exception .

**Comment by TVolden** [comment]
Oh okay, how strange. Let's get to the bottom of this.

So you have a server that is tested with the compliance tool running, and you are trying to connect with the lib as a client. Correct?
- Then the connection is closed, can you determine from which end?

**Comment by foluswen** [comment]
I have solved it, root cause is websocket draft need set to draft_13.


Folus Wen


Best Regards


*溫盛夫* *Folus Wen*
*Mobile Phone*：+886-928-455198
*e-Mail*：folus.wen@gmail.com

2017-03-21 5:57 GMT+08:00 Thomas Volden <notifications@github.com>:

**Comment by TVolden** [comment]
Hi again,

I can't see that the websocket library that I use can be set to draft_13, only: Draft 10, 17, 75 and 76.

I have investigated it, and you are absolutely correct. The websocket version that the specification refers to is draft_13:
https://tools.ietf.org/html/rfc6455#section-11.6

I will probaly have to look for a new library. 

Thank you so much for your feedback, it really means a lot to me.

**Comment by TVolden** [comment]
Good news, I may not have to change the lib I use anyway.
http://stackoverflow.com/questions/21035326/what-draft-does-java-websockets-websocketserver-use

Looks like draft_17 is used for version 13 support.

Did you have any success testing the library?

**Comment by TVolden** [comment]
I'm considering this resolved. If you're​ still experiencing problems, then please don't hesitate to open a new issue.

Thanks again for your input.
