### ISSUE TITLE
Suggestion for improvement: SOAP

### ISSUE THREAD

**Issue by davidhuwyler** [ChargeTimeEU/Java-OCA-OCPP#2]
In order to support existing charging infrastructure it would be great to have JSON & SOAP support.

Best regards
David Huwiler

**Comment by TVolden** [comment]
Hi David,

Thanks for your request. I have started to plan the work.

You can follow the status here:
https://tree.taiga.io/project/tvolden-java-oca-ocpp

**Comment by TVolden** [comment]
First push containing a SOAP client that can send messages (but not receive).

**Comment by TVolden** [comment]
The next push will have changes to models with enums and calendar dates. I have changed it so all getters have the same data type as the setters. 

**This means you have to expect a Calendar/Enum object instead of a String and the "obj"-getter alternative will be removed.**

**Why?**
I had originally applied a hotfix to cope with the fact that the JSON lib didn't convert enums and Calendar dates correctly. This only resulted in some quirky data models that won't work with other libraries.

**Why now?**
- This  is needed in order to use SOAP sterilizers. Which I'm working on currently.
- Only few people uses the lib right now, so better now than later. 

More here:
https://tree.taiga.io/project/tvolden-java-oca-ocpp/issue/46

**Comment by TVolden** [comment]
Okay, second push. Client can now send requests and receive requests. Still need to make the server in order to do a full integration test.

**Comment by TVolden** [comment]
The SOAP client/server should be fully functioning now.
I will create a release, update the guide now.

**Comment by TVolden** [comment]
Done
