### ISSUE TITLE
No main manifest attribute

### ISSUE THREAD

**Issue by aufalkhlq** [ChargeTimeEU/Java-OCA-OCPP#276]
How to fix no main manifest attribute in jar file

**Comment by TVolden** [comment]
Hi @aufalkhlq,

Thanks for your question. I'm not sure exactly what you mean. Could you be more specific? - do you get an error message that you can copy and paste into the thread?

**Comment by TVolden** [comment]
Hi @aufalkhlq 

On second inspection, I believe the problem is that there is no `main` method declared in the library. This is because this is not an application, so you can't execute the jar file.

There's a small guide to getting started here: https://github.com/ChargeTimeEU/Java-OCA-OCPP/wiki/Getting-started
If you have any questions I encourage you to use the discussion section which I just added.
