### ISSUE TITLE
Session != Client.connection

### ISSUE THREAD

**Issue by davidhuwyler** [ChargeTimeEU/Java-OCA-OCPP#3]
Hi Thomas

I think there is a Implementation problem at:  **JSONServerSample.java at line 124:**

        `server.open("localhost", 8887, new ServerEvents() {

            @Override
            public void newSession(int sessionIndex) {

                // sessionIndex is used to send messages.
                System.out.println("New session " + sessionIndex);
            }

            @Override
            public void lostSession(int sessionIndex) {

                System.out.println("Session " + sessionIndex + " lost connection");
            }
        });`

IMHO a client connection to the server is not the same as a Session. I think the client (==chargePoint) stays connected the whole time, but a OCPP-session (chargePoint session with a customer) is just held up during a interaction with one chargePoint customer.

I think the server should have seperate methode like: server.newSession / server.closeSession, without closing the client/server connection...

Do you agree?

Best regards
David

**Comment by TVolden** [comment]
Yeah okay, I see what you are saying. Session may not be the best name for that class. I choose the name, since my scope is limited to communication between nodes.

My thoughts was that a Session doesn't only hold a connection, but also has a responsibility for matching responses with the correct request. Handles errors and communicate them to the other end.
Please see ![Session](https://github.com/ChargeTimeEU/Java-OCA-OCPP/wiki/Class-roles%2C-responsibilities-and-collaborators#session) under responsibilities.

Any suggestions for a name that better suits the purpose?


> I think the server should have seperate methode like: server.newSession / server.closeSession, without closing the client/server connection...
If I understand you correct, you want the server to create a charge session, eg. starts with RemoteStart and ends with RemoteStop. Correct?
It would be cool to implement, but I think it's out of the scope of this project. The scope of the library is to manage connections, send messages, and handle errors. - All this according to the OCPP specification.

I predict a future project to setup and administer a server, eg. authorized ids (customers), sessions (transactions), statistics, charge boxes (locations and more).

**Comment by davidhuwyler** [comment]
Ok i got it. Thanks for clarifying
