### ISSUE TITLE
Command to simulate a Charge Point

### ISSUE THREAD

**Issue by ghamkhari** [ChargeTimeEU/Java-OCA-OCPP#62]
I want to simulate a Charge Point with Java-OCA-OCPP that can receive and respond to JSON messages that are sent over websocket. I have successfully built the libraries inside Java-OCA-OCPP by `mvn package` command. Now, what command should I use to simulate a Charge Point?

**Comment by TVolden** [comment]
Hi Mahdi,

You will have to do some programming in order to have a client. There isn't a out of the box application.

Take a look at the example code, to see how to implement a client:
https://github.com/ChargeTimeEU/Java-OCA-OCPP/blob/master/ocpp-v1_6-example/src/main/core_features/JSONClientSample.java

I have started a client simulator project, but at the moment it can only connect:
https://github.com/ChargeTimeEU/ChargePointSimulator

I hope it helps.

**Comment by TVolden** [comment]
I'm closing this issue, since it's not the intention of this library to implement an app.
I'd love to see projects that uses my lib to create a full central system or client.

Who knows, maybe I'll get time to continue my own application projects at one point:
https://github.com/ChargeTimeEU/ChargeTime-HQ
https://github.com/ChargeTimeEU/ChargePointSimulator
